#!/usr/bin/env bash

# Define an associative array:
typeset -A mode
# And its content:
mode=(
  	[Laptop (Hybrid)]="autorandr --load Laptop"
	[Home (Hybrid)]="autorandr --load Home"
  	[Home (Nvidia)]="autorandr --load Home-Nvidia"
	[Laptop (Nvidia)]="autorandr --load Laptop-Nvidia"
  	#[Focus]="autorandr --load focus1screen"
  	[Presentation]="xrandr --auto"
  	#[4screens]="autorandr --load 4screens"
  	[Cancel]=""
)

mode_nrows=${#mode[@]}

selected="$(printf '%s\n' "${!mode[@]}" | sort | rofi -dmenu -p "Monitor setup" -i -lines 2)"
i3-msg -q "exec --no-startup-id ${mode[${selected}]}"
